### ISSUE TITLE
Empty states in Bonus and other  payout sections does not allow

### ISSUE THREAD

**Issue by AnchalSharma77** [Krenai-Pvt-Ltd/haajari-frontend-angular12#769]

**Comment by AnchalSharma77** [comment]
Empty states in Bonus and other  payout sections  does not allow users to change date range and view the details<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/5406a81d-7636-4d90-9835-1ce2863055b3" />
@Richadxt08

**Comment by Richadxt08** [comment]
<img width="1792" alt="Screenshot 2024-12-18 at 12 46 05 PM" src="https://github.com/user-attachments/assets/75c6a28a-8851-46d4-9cb5-44babd266bb1" />
Done
