### ISSUE TITLE
Overtime and other user request counters are incorrect

### ISSUE THREAD

**Issue by AnchalSharma77** [Krenai-Pvt-Ltd/haajari-frontend-angular12#783]

**Comment by AnchalSharma77** [comment]
Marker is indicating that something is there in overtime request but it is showing no data found<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/b6d11d59-a9c6-45a6-82cc-501c9d87d595" />
@Richadxt08

**Comment by Richadxt08** [comment]
The marker indicating pending overtime requests/updation request is functioning as expected. The counter reflects pending requests from a different month, which can be viewed by adjusting the date range accordingly. This ensures that pending requests across all date ranges are accounted for.
