### ISSUE TITLE
Uuid of user is being updated from somewhere

### ISSUE THREAD

**Issue by AnchalSharma77** [Krenai-Pvt-Ltd/haajari-frontend-angular12#788]

**Comment by AnchalSharma77** [comment]
uuid of inboxjasdev@outlook.com updated from 81b1cb14-bc6b-11ef-9324-02122ed2eb01 to d9f52874-bc76-11ef-b4c4-02122ed2eb01

**Comment by Richadxt08** [comment]
<img width="1792" alt="Screenshot 2024-12-18 at 4 27 50 PM" src="https://github.com/user-attachments/assets/20cb92f9-e945-4b97-bbc8-7b2307d1ccf5" />
Done

**Comment by AnchalSharma77** [comment]
fixed and deployed
