### ISSUE TITLE
Static data in geeneerate salary slip component

### ISSUE THREAD

**Issue by AnchalSharma77** [Krenai-Pvt-Ltd/haajari-frontend-angular12#789]

**Comment by AnchalSharma77** [comment]
<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/199e9de9-490c-46a8-b11a-9ac15f733f31" />
@Abhijeet262 @krenaiYogesh

**Comment by krenaiYogesh** [comment]
Issue already fix

**Comment by AnchalSharma77** [comment]
fixed and deployed
