### ISSUE TITLE
Attendance Muster roll data is incorrect

### ISSUE THREAD

**Issue by AnchalSharma77** [Krenai-Pvt-Ltd/haajari-frontend-angular12#791]

**Comment by AnchalSharma77** [comment]
Pagination is incorrect and items per-page are not matching<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/36ca80b8-ca84-4521-86ad-6dfe42f54c25" />

**Comment by Richadxt08** [comment]
Done
![Uploading Screenshot 2024-12-18 at 3.34.07 PM.png…]()

**Comment by AnchalSharma77** [comment]
fixed and  deployed
